### ISSUE TITLE
Create separate container service to load appointment information (for usage in case editor)

### ISSUE THREAD

**Issue by crobert-betterdoc** [betterdoc-org/appointment-cs-free-slot-search#1]
## Goal

The case editor should be able to retrieve and display real free appointment slots from Borg.

## Details

In order to be able to assign an appointment slot to a case in the case editor, a new service `appointment-cs-free-slot-search` should be created that:
* provides ability to look for free appointment slots (incl. tests)
* uses direct (read-only!) access to the Borg database
* adjust `case-cs-editor` to use this service
* ensure `Appointment select XXX` is transferred to case editor form

NOTE: the direct access to the Borg Database is a *temporary* solution until the appointment system has its own data storage outside of BORG.

**Comment by babajidemm-bd** [comment]
The initial version has been deployed to t-stacker. Some UI changes are being made by Ben and Lucas.

**Comment by konstantinweiss** [comment]
@crobert-betterdoc @babajidemm-bd @lucasmetzenbd 
As far as I understand, the one aspect which is still open is a separate issue:
https://github.com/betterdoc-org/appointment-cs-free-slot-search/issues/2
And anything else is already solved. Hence, I'm closing this issue.
